mollie/Shopware

- Components/Services/BasketService.php
Tried updating the plugin today, immediately had an issue where the tax calculated for the order wasn't being sent to Mollie (total order amount didn't match the total of the order lines). 
Even though tax_show was true and show net price false, the tax wasn't being calculated. I've fixed this in this PR and also simplified the logic a little.
> Fix a bug where the vat calculation is wrong when Show Net price is false

- Components/Config.php
- Components/MollieApiFactory.php
- Components/Services/BasketService.php
- Components/Services/PaymentService.php
- Controllers/Backend/MollieOrders.php
- Resources/config.xml
- Resources/services.xml
- plugin.xml
Added a feature where Mollie's status updates are added to the status history of an order.
> Release 1.5.16

- Components/Services/BasketService.php
- When the basket has to be restored (because of failed payment and recreation of basket for retry) add attributes of the items to the restored Basket.
> MOL-23: Add Attributes from original Order Items to restored Basket

- Command/KlarnaShippingCommand.php
switching of config and api client was missing in cli command
added it and refactored the if conditions a bit with early returns
> MOL-14: use sub shop config in klarna cli command

- Controllers/Frontend/Mollie.php
due to the new feature of providing a test mode with both, live and api key in the configuration,
there is a new acceptance test that proves the usage of the subshop config in the notification endpoint
however i found out that the endpoint is not really stable. shopware error in case of throwables instead of json response.
also errors where displayed to the requester which might not be good to see ;)
so i've added a try catch with throwable catching
along with better logging and a generic error output
> NTR: improve notification endpoint exception handling

- MollieShopware.php
- plugin.xml
new changelog and version data
> NTR: new mollie plugin version 1.6.0

- Components/Services/OrderService.php
been there, saw that, improved that :D
> NTR: add comment to getMollieOrderId

- Subscriber/OrderBackendSubscriber.php
Implement Batch Processing:
For Batch Processing the Request either contains a single order, like in the normal save request, for which the id can be forwarded to the shipOrderToMollie method or it contains an array of orders for which the ids are forwarded in a foreach loop.
> MOL-20: Batch Processing

- Components/Services/CreditCardService.php
In CreditCartService a card token has been generated for B2B but never returned. Added return statement.
> MOL-21: Return CreditCardToken

- Components/Config.php
- Resources/config.xml
Added "completely paid" as option to "Status for authorized payments"
> MOL-44: Completely Paid Option

- Subscriber/OrderBackendSubscriber.php
Added Order Model Subscriber to process order status changes which haven't been processed through API or Batch Processing.
> MOL-37: Order Model Update Subscriber

- Components/Services/PaymentService.php
option to set a custom base URL for webhook URL-building.
this can then be used e.g. with ngrok or other tools
there has been such an option hardcoded in earlier version.
all i did was to make it more "stable" and "official".
you can provide a custom mollie entry in the config.php,
if a value is set, then this base URL will be used when generating a webhook URL for mollie
> MOL-54: add custom webhook URL option for local dev

- Components/CustomConfig/CustomConfig.php
- Components/Services/PaymentService.php
more easy config, refactored + separate class
> MOL-54: improve configuration for custom webhooks urls

- Command/KlarnaShippingCommand.php
some transactions are shipped but somehow are not marked as shipped in shopware.
thus, they will be retried over and over again
so i did an auto repair, to mark them as shipped in the local transaction database
i did also refactor the output a bit to have it better
> MOL-49: Klarna CLI Command auto-repair orders out of sync

- Controllers/Frontend/Mollie.php
finally found that weird bug that does not do anything
it always runs in that code even if its NULL because of the string cast :)
> MOL-55: Fix Invalid Order Error Message

- Command/KlarnaShippingCommand.php
added auto fixing for finalized mollie status like cancelled and expired
now these will be marked as "processed"
also added some small log improvements
> MOL-49: Klarna Shipping CLI for finalized payment states

- Components/ApplePayDirect/Services/ApplePayDirectDisplayOptions.php
- Resources/views/frontend/checkout/cart.tpl
i've split the cart restriction to cart TOP and BOTTOM because there are 2 places
> MOL-33: additional Apple Pay Direct restriction

- Resources/config.xml
Made Testmode config inheritable
> MOL-52: Made Testmode Config inheritable

- readme.md
> NTR: Status Badges for README

- Components/Services/BasketService.php
- Controllers/Frontend/Mollie.php
Corrected rounding Problems for BasketItems in BasketService to store the rounded Values in Database and forward them to Transaction Preparation.
> MOL-70: Correct Rounding Problem and save only rounded Values

- .gitignore
- Resources/config.xml
improved structure of plugin configuration with sections and positions
also updated texts and captions to be only 1 line and easier to understand
> MOL-67: Configuration with better wording and structure

- Components/Config.php
- Components/Services/PaymentService.php
- Resources/config.xml
add optional configuration for due date (in days) of payment "bank transfer"
if set, and > 0 it will be used
> MOL-77: plugin configuration due-date for bank transfer

- MollieShopware.php
Add Index to mol_sw_transactions on activate if the Index doesn't exist already.
> MOL-92: Add Index if not exists

- Controllers/Frontend/Mollie.php
critical ist ein bisschen übertrieben :)
> NTR: change log level for return error

- Controllers/Backend/MolliePayments.php
improved user output in the backend
> MOL-107: Update Payment Buttons improved user output

- Tests/Components/TransactionBuilder/TransactionItemBuilderTest.php
just came up with this case
it fails if rounding is removed ...so its important
> NTR: add important unit test for correct rounding

- Controllers/Backend/MollieOrders.php
the repo update code didnt work because EntityManager was NULL
also added that TODO for further discussion, not that important for now
> MOL-57: add missing EntityManager for Klarna Shipping

- Command/KlarnaShippingCommand.php
output works good
though 2 lines did not show a shipping status which is not wrong, but we can just show it, maybe it helps one day
> NTR: add shipping status in klarna cli command to output

- Components/Order/ShopwareOrderBuilder.php
on hold, in doing just to let people know
> MOL-149: Fix duplicate order confirmation mails

- Components/Helpers/MollieStatusConverter.php
- Components/Order/OrderUpdater.php
- Controllers/Frontend/Mollie.php
- Controllers/Frontend/MollieApplePayDirect.php
- Events/Events.php
- Facades/FinishCheckout/FinishCheckoutFacade.php
- Facades/Notifications/Notifications.php
add filter events for paymentStatus update and orderStatus update
any external changes by plugins will be automatically logged
> MOL-164: Add Filter Events for Status Updates

- Components/Services/PaymentMethodService.php
- Tests/Components/Installer/PaymentMethodServiceTest.php
always ensure the correct controller action is assigned in the payment methods
> MOL-168: Ensure correct payment method action after installation

- Controllers/Frontend/MollieApplePayDirect.php
- Events/Events.php
move apple pay events to constant class
and add logging if changed like with other previously added events
> MOL-239: Apple Direct Shipping Events

- .github/workflows/ci_pipe.yml
ci pipeline is now also triggered after a PR-Merge by using a Push on Master trigger
> NTR: CI Pipe on Master Push

- Components/CurrentCustomer.php
- Components/Services/BasketService.php
- Components/Services/PaymentService.php
- Services/Refund/RefundService.php
- Subscriber/OrderBackendSubscriber.php
- phpstan.neon
added more directories to inspect
and fixed some dead code
> NTR: Improve PHPStan

- Resources/services.xml
- Subscriber/ApplePaySubscriber.php
> MOL-98: Fix broken Dependency on Shopware 5.3

- Components/Config.php
- Components/MollieApi/MollieApiTester.php
- Components/MollieApiFactory.php
- Controllers/Backend/MollieConfiguration.php
- Resources/config.xml
add test api button that iterates through all shops and tests their api keys
result is in extjs notification as well as in logs
> MOL-172: Test API in plugin

- CONTRIBUTING.md
> NTR: improve contribution

- Components/Order/OrderUpdater.php
- Facades/FinishCheckout/FinishCheckoutFacade.php
an order must not get cancelled because the confirm email throws an error
so i've added a try catch and a log entry instead
> MOL-451: Ignore Mail Exception when completing an order

- Command/ShippingCommand.php
- Components/Config.php
- Facades/ShippingCommand/ShippingCommandFacade.php
- Resources/config.xml
- Resources/services/commands.xml
- Subscriber/OrderBackendSubscriber.php
added the klarna cli shipping for all payment methods, if orders api is used
moved klarna code into facade,
and both cli commands now use it
> MOL-426: CLI shipping for all payment methods

- Components/Order/OrderUpdater.php
payment status did work
but not the optional additional order status
so if 2 entries have been written, only the first one was "fetched" and thus updated
> MOL-484: Fix missing status history icon for order status transitions

- Controllers/Backend/MollieConfiguration.php
- Resources/config.xml
added button with deeplink option to the mollie dashboard api page
> MOL-177: Deeplink to Mollie API Keys from Backend

- Components/Services/PaymentMethodService.php
- Tests/PHPUnit/Services/PaymentMethodServiceTest.php
add whitelist to avoid dynamic payment methods from being added
> MOL-424: Officially supported payment methods

- Command/KlarnaShippingCommand.php
- Command/OrdersShippingCommand.php
- Command/ShippingCommand.php
- Controllers/Api/Mollie.php
- Facades/Shipping/ShipOrderFacade.php
- Facades/Shipping/ShippingCommandFacade.php
add shipOrder and shipItem as API HTTP options
extracted the code from the CLI command to a facade and reused it
> MOL-502: Shipments via Shopware API

- Command/OrdersRefundCommand.php
- Controllers/Api/Mollie.php
- Facades/Refund/RefundOrderFacade.php
add refund option to Shopware HTTP Api
extracted old CLI command into facade and reused this
> MOL-194: Refunds via Shopware API

- Resources/views/backend/mollie_extend_payment/view/payment/form_panel.js
- Tests/Cypress/cypress/support/actions/backend/ConfigSetupAction.js
- Tests/Cypress/cypress/support/repositories/backend/PaymentMethodsRepository.js
translation window was broken
had to remove the IDs, then it works again
cypress has also changed
> NTR: ExtJS IDs break snippets window

- Components/MollieApiFactory.php
- Services/Mollie/Client/MollieHttpClient.php
sometimes it could happen that there might be a curl timeout
so better increase that one, better safe than sorry
> MOL-560: Increase API Client Timeouts

- Facades/FinishCheckout/Services/MollieStatusValidator.php
somehow it seems that i can be that an expired order is returned back to the shop...for whatever reason.
this ensures that it has the same error-behaviour as failed or cancelled payments
> MOL-650: add check for expired payments in return action

- Tests/Snippets/validate.php
not all directories where correctly scanned for files
> NTR: improve snippet validation to really find all INI files

- Components/Installer/PaymentMethods/PaymentMethodsInstaller.php
- Components/Services/ShopService.php
- MollieShopware.php
- Resources/services/components/mixed.xml
Added an iteration over shops to get active payment methods for each subshop which might have different API keys.
> MOL-145 import payment methods from all api keys

- Components/Services/BasketService.php
premium products have been added as ordinary products after a failed payment
this meant that they where not free anymore
we need a special handling for this
> MOL-660: Fix bug with free premium products after a payment fails

- Components/TransactionBuilder/Services/ItemBuilder/TransactionItemBuilder.php
- Tests/PHPUnit/Components/TransactionBuilder/Services/ItemBuilder/TotalAmountTest.php
> MOL-669: Fix invalid amount for tax free countries with higher quantity

- Resources/views/frontend/plugins/payment/mollie_applepay_direct.tpl
> MOL-897 Fixed the locale of the Apply Pay Direct button
