mollie/Shopware

Controllers/Frontend/Mollie.php
When ordering from a foreign country, VAT may not be applied.
But in the order confirmation e-mail it will still be visible. By setting sNet on the Shopware Order class the VAT will not be visible in the confirmation e-mail.
=> Setting order sNet to hide the VAT

Components/Services/PaymentService.php, Controllers/Frontend/Mollie.php
if you use a non-3d secure credit card
the checkoutURL is not existing,
thus there will be an error when finishing the order
so i've added a check if its a valid "paid" credit card payment without a checkout URL...in that case its OK because it (should be) a non-3d secure card
i just redirect to the return action just as if the visitor is returning from the external mollie payment form
the order of this non-3d payment was then "paid" and completed in the shopware backend
=> MOL-4: fix checkout with NON 3D-SECURE credit cards

Components/Attributes.php
somehow the structure of the uninstaller for the CRUD handling of the entities was different in my case?
it was no key/value array
can you please verify this and only merge it if correct?
=> NTR: Fix broken CRUD uninstaller

Command/KlarnaShippingCommand.php
the klarna shipping command looks for methods with "mollie_klarna"
but these payment methods do not exist
the correct name is "mollie_klarnapaylater"
i did now use the constant for this
but was a previous name "mollie_klarna", should we support both?
=> MOL-14: Fix Klarna CLI command

Components/Helpers/MollieLineItemCleaner.php, Components/Services/PaymentService.php
sometimes the advanced promotion suite shows duplicate discount line items
and mollie api responds with "total value does not equal to sum of line item values".
so i've added a simple cleaner that removes duplicate discount items
=> MOL-15: remove duplicate advanced promotion discount items

Components/Config.php, Components/Helpers/MollieShopSwitcher.php, Components/MollieApiFactory.php, Components/Services/PaymentService.php, Controllers/Backend/MollieOrders.php, Controllers/Frontend/Mollie.php, Resources/config.xml, Subscriber/OrderBackendSubscriber.php
please test before merging
parts to test
* transition klarna order to a status that triggers the "shipping" in mollie
* a) for an order from the main shop
* b) for an order from a subshop with da different config
* ship truck icon in shopware backend
* a) for an order from the main shop
* b) for an order from a subshop with da different config
* refund action + partial refund
* a) for an order from the main shop
* b) for an order from a subshop with da different config
=> MOL-14: fix wrong mollie config for klarna shipping in subshop

Components/Services/PaymentMethodService.php
apple pay direct was disabled again after a plugin reinstall
moved the "set inactive" to the part where it creates the new payment method
=> NTR: fix disabled applepay direct after plugin reinstall

Controllers/Frontend/Mollie.php
credit card components have a test mode configuration
that needs to be changed to the new setting in the plugin
=> NTR: fix credit card components test mode due to new config

Resources/views/frontend/_public/src/js/components.js
The Default Shopware Checkout has 2 "submit" Buttons.
One above the Shipping and Payment Methods and one below.
If CreditCard ist the first selected Component while opening the checkout, the JavaScript that selects the Submit button is executed directly instead of waiting until the DOM is ready.
In the default checkout this works because we have a submit button that was printed into the dom before the javascript was executed.
Customized Checkouts with only one submit button below the payment and shipping selection will cause an JavaScript Error:
components?ext=.js&ts=1599553913:69 Uncaught (in promise) TypeError: Cannot set property 'disabled' of null
at disableForm (components?ext=.js&ts=1599553913:69)
at HTMLFormElement.<anonymous> (components?ext=.js&ts=1599553913:112)
This pull …
=> Fixed JavaScript Error for the SubmitButtons while using CreditCard

Subscriber/ApplePayDirectSubscriber.php
On switch payment ajax request the sPayments variable is null which caused a 500 Response as removeApplePayDirectFromPaymentMeans only accepts arrays
=> MOL-29: Fix Problem with sPayments = null which caused dead loading

Controllers/Frontend/Mollie.php
Remove calls for ConfigSwitcher as they caused a problem in the getOrderFromTransaction when the "Create order before payment" option setting is no as then the order doesn't exist at this point.
=> MOL-26: Fix create order after payment

Resources/views/frontend/_public/src/js/applepay.js, Subscriber/FrontendViewSubscriber.php
the original apple pay was hidden, even its a default payment method...no one knew...that was the function
i've also renamed the function and improved descriptions
=> MOL-30: Hide original Apple Pay on payment selection page

Components/Services/OrderService.php, Subscriber/OrderBackendSubscriber.php
the function getMollieOrderId($orderId)
is sometimes called with $orderID and with $order (object)
which both works...but its wrong
due to the risk of usage, i changed to order object instead of orderId, because there are more points where $order is already used
=> MOL-32: Fix wrong parameters of getMollieOrderId

Subscriber/OrderBackendSubscriber.php
this was a notifyUntil call
so with the added return statement, the mail isn't sent anymore
i've reverted it to the way it was before..without any return for success
=> MOL-31: Fix broken order confirmation mail

Controllers/Frontend/Mollie.php
There was a problem with payment methods which check if the sum of lineItem totalAmount and order totalAmount are equal that the lineItem prices haven't been rounded to 2 decimals before they are multiplied by the ordered quantity.
If you have 2 products with a price like 100.66 net and a VAT rate of 16% the unitPrice is 116.7656. Shopware rounds this to 2x 116.77 with an order total of 233.54. With the old calculation it was 2x 116.7656 = 233.5312 which is rounded to 233.53 and differs from the order total by 0.01 and causes this error.
=> MOL-24: LineItem TotalAmount Correction

Resources/views/frontend/_public/src/js/applepay-direct.js, Resources/views/frontend/checkout/ajax_cart.tpl, Resources/views/frontend/checkout/cart.tpl, Resources/views/frontend/detail/buy.tpl, Resources/views/frontend/plugins/payment/mollie_applepay_direct.tpl
if apple pay wasnt visible there were still 10px margins from the wrapping div layer.
they should be removed
that layer depends on the place where its used
so i've moved the "active" IF condition to the integration templates.
every container does now have a generic applepay-container class name that will be used to show/hide 
the whole apple pay within javascript
=> MOL-35: Improve ApplePay Direct Margins if hidden

Resources/views/frontend/_public/src/js/applepay-direct.js
the previous implementation was bound to the sQuantity dropdown when using Apple Pay on PDP
some templates might not have this
thus there is a fallback, that uses quantity 1 in case the dropdown doesnt exist in the template
=> MOL-28: Apple Pay Direct Quantity Fallback on PDP

Components/Account/Account.php, Components/ApplePayDirect/ApplePayDirectFactory.php, Components/ApplePayDirect/ApplePayDirectHandlerInterface.php, Components/ApplePayDirect/Handler/ApplePayDirectHandler.php, Components/ApplePayDirect/Models/Button/ApplePayButton.php, Components/ApplePayDirect/Models/Cart/ApplePayCart.php, Components/ApplePayDirect/Models/Cart/ApplePayLineItem.php, Components/Country/CountryIsoParser.php, Components/Order/OrderSession.php, Components/Shipping/Shipping.php, Controllers/Frontend/MollieApplePayDirect.php, Traits/MollieApiClientTrait.php, readme.md
we remove diw and kiener infos from the plugin to have it "branded" for mollie.
this should avoid direct agency support. its planned to do 1st level support only thru the official mollie support
=> NTR: remove diw and kiener

Components/Constants/PaymentStatus.php, Components/Helpers/MollieRefundStatus.php, Components/Services/PaymentService.php
notification of refunded orders have always been converted to "paid" again, which is wrong.
the problem is, that the status is still "paid" but optional refund data exists that need to be queried.
the hard thing was to add that without the risk of side effects.
so i've created a refund class that just asks for either full or partial refunds of both payments and orders in mollie.
the integration has then be done equal to the existing ones to avoid side effects
=> MOL-42: Fix missing refund status in webhooks

Components/Helpers/MollieRefundStatus.php
accidentally used shopware namespace which causes problems.
muas irgendwie eini grutscht sei beim commit, duad ma lad, gott sei dank gibts ja ne qa phase :)
=> MOL-42: Fix wrong namespace for refund webhooks

Components/Account/Account.php, Components/ApplePayDirect/ApplePayDirectHandlerInterface.php, Components/ApplePayDirect/Handler/ApplePayDirectHandler.php, Components/ApplePayDirect/Models/UserData/UserData.php, Components/Order/OrderAddress.php, Components/Order/OrderSession.php, Controllers/Frontend/MollieApplePayDirect.php
if the user is already signed in, apple pay direct should use this user instead of creating a guest account.
the user data by apple pay is now stored in the session.
if required, a guest account is being created.
however in both cases, it will be ensured that the order will get the data from apple pay
=> MOL-41: Apple Pay Direct with logged in Shop Account

Components/ApplePayDirect/Models/Button/ApplePayButton.php, Components/ApplePayDirect/Models/Button/DisplayOption.php, Components/ApplePayDirect/Services/ApplePayButtonBuilder.php, Components/ApplePayDirect/Services/ApplePayDirectDisplayOptions.php, Components/Config.php, Controllers/Backend/MollieApplePayDirect.php, Resources/config.xml, Resources/services/applepay_direct.xml, Resources/views/frontend/checkout/ajax_cart.tpl, Resources/views/frontend/checkout/cart.tpl, Resources/views/frontend/detail/buy.tpl
added new plugin configuration to restrict the apple pay direct display on certain pages.
the button settings do now come with display options, where a restriction would lead to "visible = false"
=> MOL-33: add Apple Pay Direct display option

Components/Services/BasketService.php, Components/Services/PaymentService.php, Controllers/Backend/MollieOrders.php
Remove the OrderHistoryService calls as the order and payment history entries are already set in the setPaymentStatus and setOrderStatus Shopware methods.
=> MOL-43: Remove History Duplicates

Components/Services/PaymentMethodService.php
somehow getActivePaymentMethodsFromMollie is null
this seems to be due to a missing api key
i think there is something weird anyway in the installation process
i'just tried to avoid that exception, then it works and just doesnt install anything
could you double check @barbieswimcrew  (that was your code - just to be sure)
=> MOL-74: Fix broken payment installation without Live API key

Resources/config.xml
if plugin is installed and cache is not cleared, the configuration backend URL does not yet exist, which leads to a huge extJs error display
the only solution now is, to throw an exception with a message and avoid that huge alert from being displayed
=> MOL-73: Hide ExtJS error for ApplePay Display restrictions

.gitignore, .travis.yml, Components/Basket/Basket.php, Components/MollieApi/LineItemsBuilder.php, Components/Services/BasketService.php, Components/Services/PaymentService.php, Components/Shipping/Models/ShippingCosts.php, Components/Shipping/Providers/CartShippingCostsProvider.php, Components/Shipping/Shipping.php, Components/Shipping/ShippingCostsProviderInterface.php, Components/TransactionBuilder/Models/BasketItem.php, Components/TransactionBuilder/Models/TaxMode.php, Components/TransactionBuilder/TransactionItemBuilder.php, Controllers/Frontend/Mollie.php, Resources/services.xml, Resources/services/components.xml, Tests/Components/ApplePayDirect/Models/Button/ApplePayButtonTest.php, Tests/Components/ApplePayDirect/Models/Cart/ApplePayCartTest.php, Tests/Components/ApplePayDirect/Services/ApplePayDomainFileDownloaderTest.php, Tests/Components/Logger/Services/IPAnonymizerTest.php, Tests/Components/MollieApi/LineItemsBuilderTest.php, Tests/Components/TransactionBuilder/TransactionItemBuilderTest.php, composer.json, makefile, phpunit.xml
=> MOL-75: Refactoring of line item rounding

Components/TransactionBuilder/Models/BasketItem.php, Controllers/Frontend/Mollie.php, Tests/Components/TransactionBuilder/Models/BasketItemTest.php
shippings have been converted to gross twice 
articles have either gross or net price in UnitPrice
shippings have ALWAYS gross in there
so we need to change the mode in that to be like "articles" for the transaction item builder
=> MOL-75: Rounding Refactoring fix Shipping Costs

Components/ApplePayDirect/Services/ApplePayFormatter.php, Controllers/Frontend/MollieApplePayDirect.php, MollieShopware.php, Resources/services.xml, Resources/services/subscriber.xml, Subscriber/TestModeSubscriber.php
mollie payment methods will now get a TEST_MODE suffix in test mode
a test subscriber handles account, confirm, payment, and finish
and adds Mollie Test Mode only to mollie payments
apple pay will show Test Mode also in the payment sheet as shop name
(without mollie, because its clear what it is)
=> MOL-65: Show test mode information in storefront

Controllers/Frontend/Mollie.php, Facades/CheckoutSession/CheckoutSessionFacade.php, Services/TokenAnonymizer/TokenAnonymizer.php, Tests/Services/TokenAnonymizer/TokenAnonymizerTest.php, composer.json
we sometimes have to debug i payment tokens are correctly used and existing
so it will now add tehese to the initial log entry
its of course anonymized and tested
=> MOL-117: Add anonymized payment token to logs

Controllers/Frontend/Mollie.php, Facades/FinishCheckout/FinishCheckoutFacade.php, Facades/FinishCheckout/Services/ConfirmationMail.php, MollieShopware.php
Move unsetting of ordermail variables to return action to also unset them when payment failed.
Add cleanup to activate action of plugin to clean up old ordermail variables.
=> MOL-100: Cleanup ordermailVariables and unset them

Components/Services/PaymentService.php, Controllers/Frontend/Mollie.php, Facades/CheckoutSession/CheckoutSession.php, Facades/CheckoutSession/CheckoutSessionFacade.php
apple pay direct does now also NOT have a checkout url which was missing in  the orders api
also renamed the non-3d-secure to be more generic and tell what it actually does
"redirect to mollie required" yes/no
=> MOL-126: Fix Apple Pay Direct for Orders API

Components/Order/OrderCancellation.php
After a failed payment the original order has been canceled first and the quantity has been set to 0, then the basket has been restored and so it couldn't load the original quantity. 
Changed the order of cart restore and order cancellation.
=> MOL-123: Cancel Order and reset Quantity after basket restore

Controllers/Frontend/Mollie.php, Facades/CheckoutSession/CheckoutSessionFacade.php, Facades/Notifications/Notifications.php
some webhooks are way too fast
the only way to recognize this at the moment is to see if there would be a POST variable "id"
and our matching id in the database is still empty
then just skip
using the sent id could be done in the future (added a TODO)
also updated some logs for better webhooks and logging
=> MOL-125: Skip Webhooks that come in too fast

Components/Order/OrderCancellation.php, Components/Services/PaymentService.php
Invoice and Shipping Reset has only been allowed when Stock Reset was enabled. This hasn't been mentioned in Config and also it could be useful to allow it when Stock Reset is disabled. So made it independent.
=> MOL-124: Allow Invoice and Shipping Reset independent from Stock Reset

Resources/views/frontend/_public/src/js/applepay-direct.js
the session was not completed
thus it did not always work as expected the second time (it hanged)
and the feedback on iPhone or watch devices was sometimes "failed"
=> MOL-122: Apple Pay Direct Session was not completed

Components/Helpers/MollieStatusConverter.php
just found a bug
i dont know if that mapping was always missing :) but now it shows an error which might be misleading
=> NTR: add missing status mapping for failed

Resources/views/frontend/_public/src/js/applepay-direct.js, plugin.xml
The Apple pay integration causes issues when run in the internet explorer. These problems are caused by the not-existing EcmaScript compatability and are fixed by these changes
=> [MOL-104] Make applepay integration IE11 compatible.

Components/Services/OrderService.php, Components/Shipping/Providers/CartShippingCostsProvider.php, Exceptions/OrderNotFoundBySessionIdException.php, Resources/services.xml
The shipping costs have been calculated by the Admin shipping costs settings. As other plugins may add surcharges to the shipping costs this caused a difference between order total (in which the shipping surcharges were included) and the transmitted shipping costs because the calculated total and transmitted total were different.
The shipping costs are already saved calculated in the order, so use the order shipping costs for Mollie transaction.
=> MOL-76: Shipping Cost Improvement

Components/Services/OrderService.php, Components/Shipping/Providers/CartShippingCostsProvider.php, Exceptions/OrderNotFoundBySessionIdException.php, Resources/services.xml
In case of Direct Payments a Fallback has been added which reads the ShippingCost Settings from Backend and calculates the Shipping Costs.
This PR is based on MOL-76
=> Mol 129/fallback shipping costs for direct payments

Components/Constants/ShopwarePaymentMethod.php, Subscriber/ApplePayDirectSubscriber.php
if the payment fails, the confirm page is visible,
in that case we have to ensure to switch from apple pay direct to apple pay (normal payment method)
this also works if you have a successfull apple pay direct payment as last payment
and do another order with normal workflow. then apple pay will be preselected
=> MOL-68: Prevent Apple Pay Direct on confirm page

Components/Order/ShopwareOrderBuilder.php, Components/Services/OrderService.php, Controllers/Frontend/Mollie.php, Facades/FinishCheckout/FinishCheckoutFacade.php, Facades/FinishCheckout/Services/ShopwareOrderUpdater.php
if you configure to create shopware orders AFTER the payment, these orders will be created
when the user is being redirected back from Mollie to Shopware.
if the returnURL is called again after a while (manually....), or somehow multiple times due to a "back-forth" in the browser (weird behaviour when user click around randomly?!) during a real checkout....then the orders are created again.
the problem is a bug when using the Orders API...so the transaction ID "ord_xyz" is coming in, but the Shopware order will get the connected Transaction ID of the payment as transaction number which is, "tr_xyz".
So next time, when "ord_xyz" comes in, it cannot find an order because it would be "tr_xyz"...and then creates it again.
This also happens when another transaction number is used....so like …
=> MOL-135: avoid duplicate orders due to multiple return-url calls

Facades/FinishCheckout/FinishCheckoutFacade.php, Facades/FinishCheckout/Services/ShopwareOrderUpdater.php
the new payment transaction usage wasnt applied on existing orders when these
are created before the payment
in that case we need the update again
=> MOL-135: fix for payment-reference usage when order before payment

Command/PaymentImportCommand.php, Components/ApplePayDirect/Services/ApplePayPaymentMethod.php, Components/Installer/PaymentMethods/IconHtmlBuilder.php, Components/Services/PaymentMethodService.php, Controllers/Backend/MolliePayments.php, MollieShopware.php, Resources/services.xml, Resources/views/frontend/plugins/payment/methods/main.tpl
payment methods can now be imported with button since a while
unfortunately the deactivated payment methods got activated again
so i've refactored the full payment method installer.
it will checkf if methods are new, or just need to be updated, or even removed
it will also make sure that all things that can be changed by the merchant will not be overwritten again on an import (such as the active field)
i did also add better logs, and a CLI command that i used for development purpose, makes sense i think...
=> MOL-148: Improve Payment Method Imports

Command/PaymentImportCommand.php, Components/Services/PaymentMethodService.php, Controllers/Backend/MolliePayments.php, MollieShopware.php
found a new case
when uninstalling the plugin, payments are disabled
but when being installed again, they should be activated again, 
except the deprecated ones that might not exist anymore ;)
=> MOL-148: Payment installation after uninstalling plugin

Components/Shipping/Providers/CartShippingCostsProvider.php
In earlier versions of Shopware the getInvoiceShippingTaxRate Method as well as the invoice_shipping_tax_rate column in the order table don't exist. So check if the method exists, otherwise calculate the tax rate by invoice shipping and invoice shipping net.
=> MOL-158: Test if getInvoiceShippingTaxRate Method exists

Command/OrdersRefundCommand.php, Command/PaymentImportCommand.php, Components/MollieApiFactory.php, Components/Order/OrderCancellation.php, Controllers/Backend/MollieOrders.php, Controllers/Backend/MolliePayments.php, Controllers/Frontend/Mollie.php, Controllers/Frontend/MollieApplePayDirect.php
had to revert to exception instead of throwable...php 5.6 compatibility :) 
also found an issue where php 5.6 cart restoring istn working due to int/string comparison
=> MOL-240: PHP 5.6 Compatiblity Fixes

Components/Helpers/MollieStatusConverter.php, Components/Order/OrderUpdater.php, Exceptions/PaymentStatusNotFoundException.php, Facades/Notifications/Notifications.php
expired status mapping was just missing for the orders api
that means there was an error in the notification when expired has been received
i did also improve the logs a bit
=> Fix Missing Expired Mapping in Order API notifications

Components/Services/BasketService.php, Resources/services.xml
Added Compatibility for Restore Basket (create order before Payment) for SWAG Custom Products Plugin
The SWAG Custom Products Plugin generates Hashes for the possible Configurations. These are stored in the OrderItem and read from the Request when the Item is added to the Basket. Depending on the Hash and the Configuration for the Hash it adds the configuration Items (Mode 4, Surcharge/Discount Mode) and the normal Execution of the sAddArticle Method from sBasket is stopped afterwards.
So for adding Compatibility for this Plugin check if the Hash exists in the orderDetails Object Attributes and if yes store it in the Request.
=> MOL-352: Basket Restore for SWAG Custom Products Plugin

Models/TransactionRepository.php, composer.json, phpstan.neon
wanted to improve phpstan and found a new repo that requires shopware as dev dependency
so i've added shopware as require-dev and PHPStan now sees the models folders as OK :)
...also had to remove the argument types in the constructor...but now it works for stan
=> NTR: Shopware as Dev Dependency

Components/Services/PaymentService.php, Exceptions/MolliePaymentNotFound.php, Facades/FinishCheckout/FinishCheckoutFacade.php, Facades/Notifications/Notifications.php, Models/TransactionRepository.php
In the Logs of MOL-197 can be found the following Error: "error":"Call to a member function getMollieOrderId() on null"
This can only happen in PaymentService, as at all other places where this method is called it's checked before the method call if the object is of the right type.
In PaymentService I found unnecessary loading of the transaction to get the orderId (which caused the error when the loading returned null) although the transaction is already present and checked in all places where this method of the PaymentService is used, so I added the orderId as parameter for the method and don't try to load the transaction. 
The exactly same happend in the method to load the Mollie Payment.
=> MOL-197: Improved getting Mollie Orders and Payments

Command/KlarnaShippingCommand.php, Facades/CheckoutSession/CheckoutSessionFacade.php, Gateways/Mollie/MollieGateway.php, Gateways/MollieGatewayInterface.php, Models/Transaction.php, Models/TransactionRepository.php, Resources/services.xml
the idea of this PR was just a simple one, it ended a bit different :D  
the klrana shipping CLI just makes sure to go though all orders that are not shipped in Shopware and ship it, if a specific order status is set for an order.
there are different checks like "is order existing", "is already shipped" and more.
Unfortunately due to the  checkout flow design, it can be that an order is NOT existing, which is totally fine because the payment failed...thats why its not existing.
the previous code did add a log entry which caused problems for merchants....and also it got retried over and over again...
its not possible to check for a failed order with the shopware data without a real order :)
but its possible to ask mollie for their order data and get that data.
so if Mollie says its not …
=> MOL-351: Klarna CLI mark invalid orders as processed

Components/Constants/PaymentStatus.php, Components/Helpers/MollieStatusConverter.php, Components/Order/OrderUpdater.php, Components/Services/PaymentService.php, Components/StatusConverter/DataStruct/StatusTransactionStruct.php, Components/StatusConverter/OrderStatusConverter.php, Components/StatusConverter/PaymentStatusConverter.php, Tests/PHPUnit/Components/StatusConverter/OrderStatusConverterTest.php, Tests/PHPUnit/Components/StatusConverter/PaymentStatusConverterTest.php
add missing mapping for status "paid" in payments api
so both "paid" and "completed" will now lead to an order status COMPLETED
i did also encapsulate the mappings into unit tested converters for both
the payment status and order status
so our unit tests do no provide a good overview, on WHAT is being used WHEN
=> MOL-115: Paid Order Status was not updated in Payments API

Components/Helpers/MollieStatusConverter.php, Components/StatusConverter/OrderStatusConverter.php, Components/StatusConverter/PaymentStatusConverter.php
the pending state was missing for the orders api
added, and its now working 
also renamed 2 exception because the same one is somewhere else (required)
=> MOL-431: Fix missing Open status in Orders API

Components/Order/OrderUpdater.php
somehow the transition is null in some cases for a merchant
added a condition to avoid at least an exception, still its weird
=> MOL-456: Fix exception if previous order status is empty

Controllers/Backend/MollieOrders.php, Gateways/Mollie/MollieGateway.php, Gateways/MollieGatewayInterface.php, Models/TransactionRepository.php, MollieShopware.php, Resources/snippets/backend/mollie/general.ini, Resources/views/backend/mollie_extend_order/view/detail/overview.js
added new live preview of the mollie payment data in the shopware backend.
the orders detail overview has been extended with a new section
that shows data for the payment
the data will be fetched from a backend controller.
there are also 2 copy clipboard buttons and a deep-link button to open the payment in the mollie dashboard
=> MOL-181: Payment Link in Shopware Backend

Components/Config.php, Components/ConfigInterface.php, Components/Order/OrderUpdater.php, Components/Validator/PaymentStatusMailValidator.php, Tests/PHPUnit/Components/Validator/PaymentStatusMailValidatorTest.php, Tests/PHPUnit/Utils/Fakes/Config/FakeConfig.php
if payment status mails are enabled, the customer gets a paid-mail when mollie sends "paid" or completed for klarna.
the problem is, that this is only between the merchant and mollie.
the customer himself did not pay to klarna yet.
this mail would confuse him, so we make sure to always skip it
=> MOL-489: Skip Klarna Paid Status Mails

Components/Services/PaymentService.php
removed the exception catching that throws a new exception with a useless message :)
just removed it to really get errors immediately including the correct text
=> NTR: improve exception handling when shipping orders

Command/KlarnaShippingCommand.php, Command/ShippingCommand.php, Components/Mollie/MollieShipping.php, Components/Services/PaymentService.php, Controllers/Backend/MollieOrders.php, Resources/services/commands.xml, Tests/PHPUnit/Components/Mollie/Shipping/MollieShippingTest.php
had to change tracking URL building to smarty, because it involves smarty variables.
unknown smarty variables where accidentally kept in the url which leads to an invalid URL (....{$xyz}...)
thx to the smarty version, unknown variables will be removed automatically,
while still additional url checks persist in the code
also added an additional officially supported variable offerPosition.trackingcode
=> MOL-499: Support additional tracking variables in shipments

Components/Mollie/Builder/MolliePaymentBuilder.php, Components/Services/PaymentService.php, Controllers/Frontend/Mollie.php, Facades/CheckoutSession/CheckoutSessionFacade.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/ApplePayTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/BancontactTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/BankTransferTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/BelfiusTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/CreditCardTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/EPSTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/GiropayTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/IDealTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/KBCTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/PayLaterTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/PaypalTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/Przelewy24Test.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/SepaDirectDebitTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/SliceItTest.php, Tests/PHPUnit/Services/Mollie/Payments/Requests/SofortTest.php, Tests/PHPUnit/Utils/Fixtures/PaymentAddressFixture.php, Tests/PHPUnit/Utils/Traits/PaymentTestTrait.php
the code did always use the default shipping address the customer
and not the shipping address that has been used in the order
the address IDs are not available in the transaction (only customer id)
so i just use the default shopware session data that has both IDs.
the payment builder will then fetch the addresses with those IDs instead of the customers default addresses
=> MOL-508: Fix different shipping address for orders

Facades/FinishCheckout/FinishCheckoutFacade.php, Gateways/Mollie/MollieGateway.php, Gateways/MollieGatewayInterface.php, Tests/PHPUnit/Utils/Fakes/Gateway/FakeMollieGateway.php
this feature already exists for orders in mollie
now its also possible for transactions either as standalone payment or the connected payment of the order
...both should be updated
=> MOL-608: Update payment descriptions after Shopware order is created

Controllers/Frontend/Mollie.php, Facades/Notifications/Notifications.php
one a "paid" webhooks is received, we set the cleared date (paid on) while its still empty
then this shopware default field is also working with mollie
=> MOL-649: set cleared date on paid webhooks

Components/Account/Account.php, Components/Account/Exception/RegistrationMissingFieldException.php, Components/ApplePayDirect/Models/Button/ApplePayButton.php, Components/ApplePayDirect/Services/ApplePayButtonBuilder.php, Components/Translation/FrontendTranslation.php, Controllers/Frontend/MollieApplePayDirect.php, Resources/services/components/applepay_direct.xml, Resources/services/components/mixed.xml, Resources/snippets/frontend/mollie/plugins.ini, Resources/views/frontend/_public/src/js/applepay-direct.js, Resources/views/frontend/detail/index.tpl, Resources/views/frontend/plugins/payment/mollie_applepay_direct.tpl, Subscriber/FrontendViewSubscriber.php, Tests/PHPUnit/Components/ApplePayDirect/Models/Button/ApplePayButtonTest.php, Traits/Controllers/RedirectTrait.php, makefile
this pull request makes sure to also require a phone number in apple pay direct, if configured in the shop.
the shop configuration will be passed on to apple pay, which will then add that requirement in javascript.
the data is then added in the post variables.
the php action will then also add the phone number to the registration.
the error handling has been improved in case something (or other keys) are not passed on.
violation exceptions now lead to a custom RegistrationInvalidField exception with more data about that field.
errors like these will then be shown on the PDP, because registration was not complete, means that the user cannot be forwarded to the cart to finish the checkout.
to show these errors on the PDP, an existing subscriber had to be modified to allow that, as well as a …
=> MOL-688: Apple Pay Direct support for required phone numbers

Components/Basket/Basket.php
had the case of a plugin update while testing again before the release
where the cache was not really cleared...this screwed up the PDP addToCart with error 500
just added that check...better safe than sorry
=> MOL-186: add voucher fail-safe if cache was not cleared

Components/Attributes.php
Shopware offers an interface for the Crud Attribute Service. This should be used instead of the implementing service. Otherwise the service behind the interface can never be replaced or decorated.
=> Fix: Use Shopware attribute crud interface instead the service

Components/Services/CreditCardService.php, Components/Services/PaymentService.php, Exceptions/CustomerNotFoundException.php, Facades/CheckoutSession/CheckoutSessionFacade.php, Resources/services/components/mixed.xml
I added extra logging around retrieving the credit card payment token. There's an exception in the `CreditCardService` now that, when thrown, is catched in a try/catch block.
I believe the method could throw an exception, and thereby the checkout would fail, even if the token isn't required to finish the payment. To prevent that from happening, I catch the exception thrown by the `getCardToken` method (in `Components/Services/CreditCardService.php`) and log it.
=> MOL-896 fatal error on credit card service
